language: ruby
services:
  - redis-server
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-2.1.1
  - 2.0.0
branches:
  only:
    - master
notifications:
  irc: "irc.freenode.org#sidekiq"
  email:
    recipients:
      - sidekiq@librelist.org
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2.1.1
